
import { BoonDatabase } from './types';

export const BOON_DATABASE: BoonDatabase = {
  Aphrodite: [
    { name: "Flutter Strike", slot: "Attack", element: "Water", effect: "Your Attacks deal more damage to nearby foes.", statLabel: "Close-Up Damage", values: { common: "+80%", rare: "+100%", epic: "+120%", heroic: "+140%" } },
    { name: "Flutter Flourish", slot: "Special", element: "Water", effect: "Your Specials deal more damage to nearby foes.", statLabel: "Close-Up Damage", values: { common: "+100%", rare: "+150%", epic: "+200%", heroic: "+250%" } },
    { name: "Rapture Ring", slot: "Cast", element: "Air", effect: "Your Casts inflict Weak, and damage foes while dragging them toward the center.", statLabel: "Cast Damage", values: { common: "10", rare: "15", epic: "20", heroic: "25" } },
    { name: "Passion Rush", slot: "Sprint", element: "Air", effect: "Rushing damages surrounding foes and inflicts Weak, and again once you stop.", statLabel: "Blast Damage", values: { common: "20", rare: "30", epic: "40", heroic: "50" } },
    { name: "Glamour Gain", slot: "Magick", element: "Air", effect: "You automatically inflict Weak on nearby foes and gradually restore Magick near them.", statLabel: "Magick Restoration", values: { common: "6", rare: "8", epic: "10", heroic: "12" } },
    { name: "Shameless Attitude", slot: "Passive", element: "Air", effect: "You deal more damage. While you have at least 80% Health, the bonus is doubled.", statLabel: "Bonus Damage", values: { common: "+5%", rare: "+7%", epic: "+9%", heroic: "+11%" } },
    { name: "Spiritual Affirmation", slot: "Passive", element: "Air", effect: "Gain Health and MagickUp now and for the rest of this night.", statLabel: "Bonus Gain", values: { common: "+15%", rare: "+20%", epic: "+25%", heroic: "+30%" } },
    { name: "Healthy Rebound", slot: "Passive", element: "Water", effect: "Whenever you exit a Location, restore 100% Health if you have not lost too much.", statLabel: "Min Life", values: { common: "80%", rare: "70%", epic: "60%", heroic: "50%" } },
    { name: "Broken Resolve", slot: "Passive", element: "Water", effect: "Your Weak effects are more potent.", statLabel: "Weak Dmg Reduction", values: { common: "+10%", rare: "+12%", epic: "+14%", heroic: "+16%" } },
    { name: "Sweet Surrender", slot: "Passive", element: "Water", effect: "Weak-afflicted foes take more damage.", statLabel: "Damage vs Weak", values: { common: "+10%", rare: "+15%", epic: "+20%", heroic: "+25%" } },
    { name: "Heart Breaker", slot: "Passive", element: "Water", effect: "Whenever you use 40 Magick, create a Heartthrob.", statLabel: "Area Damage", values: { common: "80", rare: "100", epic: "120", heroic: "140" } },
    { name: "Secret Crush", slot: "Passive", element: "Air", effect: "Your Attacks gain Power, but you Prime 20 Magick.", statLabel: "Bonus Power", values: { common: "+5", rare: "+7", epic: "+9", heroic: "+11" } },
    { name: "Wispy Wiles", slot: "Infusion", effect: "Gain a chance to Dodge for each Air you have.", statLabel: "Dodge per Air", values: { common: "+2%" } },
    { name: "Nervous Wreck", slot: "Legendary", element: "Air", effect: "Whenever you inflict Weak, also randomly inflict Curses from other Olympians.", statLabel: "Bonus Curses", values: { common: "3" } },
    { name: "Romantic Spark", slot: "Duo", element: "Aether", effect: "Whenever you Sprint into foes with Blitz, the effect strikes right away for more damage.", statLabel: "Bonus Blitz Dmg", values: { common: "+80%" } },
    { name: "Ecstatic Obsession", slot: "Duo", element: "Aether", effect: "As long as multiple foes are in an Encounter, automatically inflict Charm on 1 of them.", statLabel: "Min Foes", values: { common: "2" } },
    { name: "Island Getaway", slot: "Duo", element: "Aether", effect: "You take less damage from nearby foes. Boons of Aphrodite treat all foes as nearby.", statLabel: "Dmg Resistance", values: { common: "+15%" } },
    { name: "Hearty Appetite", slot: "Duo", element: "Aether", effect: "You deal more damage the more Health you have.", statLabel: "Dmg per 100 Life", values: { common: "+10%" } },
    { name: "Sunny Disposition", slot: "Duo", element: "Aether", effect: "Whenever you create Heartthrobs, create more.", statLabel: "Bonus Heartthrobs", values: { common: "+2" } },
    { name: "Burning Desire", slot: "Duo", element: "Aether", effect: "While foes are Weak, any Scorch they have does not diminish as it deals damage.", statLabel: "Duration", values: { common: "∞" } },
    { name: "Love Handles", slot: "Duo", element: "Aether", effect: "Your blast effects from Hephaestus also create a Heartthrob.", statLabel: "Area Damage", values: { common: "120" } },
    { name: "Carnal Pleasure", slot: "Duo", element: "Aether", effect: "Whenever you collect a Plasma, create a Heartthrob.", statLabel: "Chance", values: { common: "25%" } }
  ],
  Apollo: [
    { name: "Nova Strike", slot: "Attack", element: "Air", effect: "Your Attacks deal more damage in a larger area.", statLabel: "Attack Damage", values: { common: "+40%", rare: "+60%", epic: "+80%", heroic: "+100%" } },
    { name: "Nova Flourish", slot: "Special", element: "Air", effect: "Your Specials deal more damage in a larger area.", statLabel: "Special Damage", values: { common: "+60%", rare: "+80%", epic: "+100%", heroic: "+120%" } },
    { name: "Solar Ring", slot: "Cast", element: "Fire", effect: "Your Casts inflict Daze, and deal a burst of damage before they expire.", statLabel: "Burst Damage", values: { common: "80", rare: "120", epic: "160", heroic: "200" } },
    { name: "Blinding Rush", slot: "Sprint", element: "Fire", effect: "Your Sprint is faster and inflicts Daze on surrounding foes.", statLabel: "Speed", values: { common: "+15%", rare: "+20%", epic: "+25%", heroic: "+30%" } },
    { name: "Lucid Gain", slot: "Magick", element: "Air", effect: "Whenever your Cast expire, restore Magick.", statLabel: "Magick Restored", values: { common: "40", rare: "60", epic: "80", heroic: "100" } },
    { name: "Light Smite", slot: "Passive", element: "Fire", effect: "After you take damage, your foe takes damage and you inflict Daze on all foes in the vicinity.", statLabel: "Revenge Damage", values: { common: "50", rare: "75", epic: "100", heroic: "125" } },
    { name: "Perfect Image", slot: "Passive", element: "Air", effect: "You deal more damage until you take damage. If you take no more for 15 Sec., regain this.", statLabel: "Bonus Damage", values: { common: "+10%", rare: "+15%", epic: "+20%", heroic: "+25%" } },
    { name: "Dazzling Display", slot: "Passive", element: "Fire", effect: "Your attacks may inflict Daze.", statLabel: "Daze Chance", values: { common: "+10%", rare: "+15%", epic: "+20%", heroic: "+25%" } },
    { name: "Back Burner", slot: "Passive", element: "Fire", effect: "Foes with Daze take more damage if struck from behind.", statLabel: "Backstab Damage", values: { common: "+50%", rare: "+75%", epic: "+100%", heroic: "+125%" } },
    { name: "Prominence Flare", slot: "Passive", element: "Fire", effect: "After your Ω Cast expires, rapidly deal damage in the area for 2 Sec.", statLabel: "Damage", values: { common: "10", rare: "12", epic: "14", heroic: "16" } },
    { name: "Super Nova", slot: "Passive", element: "Air", effect: "Your Casts expand in size until they expire.", statLabel: "Max Size", values: { common: "+40%", rare: "+50%", epic: "+60%", heroic: "+70%" } },
    { name: "Extra Dose", slot: "Passive", element: "Air", effect: "Your Attack has a chance to hit 2 times.", statLabel: "Chance", values: { common: "+5%", rare: "+8%", epic: "+10%", heroic: "+13%" } },
    { name: "Self Healing", slot: "Infusion", effect: "While you have at least 3 Fire, whenever you take damage, restore some Health.", statLabel: "Recovered", values: { common: "30%" } },
    { name: "Exceptional Talent", slot: "Legendary", element: "Fire", effect: "Your Ω Attack and Ω Special fire 2 times, but use more Magick.", statLabel: "Cost Increase", values: { common: "+20" } },
    { name: "Glorious Disaster", slot: "Duo", element: "Aether", effect: "You can Channel +30 Magick into your Ω Cast to repeatedly strike foes with lightning bolts.", statLabel: "Bolt Damage", values: { common: "20" } },
    { name: "Sun Worshiper", slot: "Duo", element: "Aether", effect: "In each Encounter, the first foe you slay returns to fight for you.", statLabel: "Servant Dmg", values: { common: "+200%" } },
    { name: "Beach Ball", slot: "Duo", element: "Aether", effect: "Your Sprint creates a watery globe behind you, which surges ahead once you stop.", statLabel: "Max Blast Dmg", values: { common: "300" } },
    { name: "Tropical Cyclone", slot: "Duo", element: "Aether", effect: "While standing in a Gust, you randomly fire gales every 0.3 Sec.", statLabel: "Gale Damage", values: { common: "70" } },
    { name: "Warm Breeze", slot: "Duo", element: "Aether", effect: "Whenever you Dodge or Daze causes a foe to miss, restore some Health.", statLabel: "Life Restored", values: { common: "10" } },
    { name: "Rude Awakening", slot: "Duo", element: "Aether", effect: "Your blast effects from Hephaestus clear Daze and deal more damage if they do.", statLabel: "Bonus Dmg", values: { common: "300" } },
    { name: "Cutting Edge", slot: "Duo", element: "Aether", effect: "Your falling blades from Ares drop +1 time in succession and deal damage in a larger area.", statLabel: "AoE", values: { common: "+50%" } }
  ],
  Ares: [
    { name: "Vicious Strike", slot: "Attack", element: "Earth", effect: "Your Attacks deal more damage and inflict Wounds.", statLabel: "Attack Damage", values: { common: "+20%", rare: "+30%", epic: "+40%", heroic: "+50%" } },
    { name: "Vicious Flourish", slot: "Special", element: "Earth", effect: "Your Specials deal more damage and inflict Wounds.", statLabel: "Special Damage", values: { common: "+30%", rare: "+40%", epic: "+50%", heroic: "+60%" } },
    { name: "Sword Ring", slot: "Cast", element: "Earth", effect: "Your Casts create a falling blade over each foe in the binding circle.", statLabel: "Blade Damage", values: { common: "80", rare: "110", epic: "140", heroic: "170" } },
    { name: "Stabbing Rush", slot: "Sprint", element: "Earth", effect: "Your Dash creates a row of falling blades along your path.", statLabel: "Blades Damage", values: { common: "30", rare: "45", epic: "60", heroic: "75" } },
    { name: "Grisly Gain", slot: "Magick", element: "Earth", effect: "Striking foes with your Weapon may spill Plasma, which also restores 15 Magick.", statLabel: "Chance", values: { common: "10%", rare: "12%", epic: "14%", heroic: "16%" } },
    { name: "Meat Grinder", slot: "Passive", element: "Earth", effect: "Your Ω Cast also creates a Blade Rift in the binding circle.", statLabel: "Rift Damage", values: { common: "30", rare: "40", epic: "50", heroic: "60" } },
    { name: "Profuse Bleeding", slot: "Passive", element: "Earth", effect: "Whenever foes with Wounds take damage, they may spill Plasma.", statLabel: "Chance", values: { common: "+10%", rare: "+15%", epic: "+20%", heroic: "+25%" } },
    { name: "Grievous Blow", slot: "Passive", element: "Earth", effect: "Foes with Wounds may suffer 200% damage when struck.", statLabel: "Double Dmg Chance", values: { common: "+10%", rare: "+15%", epic: "+20%", heroic: "+25%" } },
    { name: "Visceral Impact", slot: "Passive", element: "Earth", effect: "Afer you take damage or a foe is slain, spill Plasma, sometimes twice.", statLabel: "Bonus Chance", values: { common: "25%", rare: "35%", epic: "45%", heroic: "55%" } },
    { name: "Mutual Destruction", slot: "Passive", element: "Earth", effect: "Gain a chance to deal 200% damage that increases the less Health you have remaining.", statLabel: "Chance/HP", values: { common: "0.1%", rare: "0.12%", epic: "0.14%", heroic: "0.16%" } },
    { name: "Blood Spree", slot: "Passive", element: "Earth", effect: "While you have less than 40 Health, your Attacks and Specials restore Health.", statLabel: "Restoration", values: { common: "1", rare: "2", epic: "3", heroic: "4" } },
    { name: "Cut Above", slot: "Passive", element: "Earth", effect: "Your Ω Moves also cause a falling blade to appear over each foe stroke, but use +5 Magick.", statLabel: "Blade Damage", values: { common: "90", rare: "120", epic: "150", heroic: "180" } },
    { name: "Rallying Cry", slot: "Infusion", effect: "While you have at least 8 Earth, any of your damaging effects from Olympians are stronger.", statLabel: "Bonus Damage", values: { common: "+50%" } },
    { name: "Sanguinary Savor", slot: "Legendary", element: "Earth", effect: "Any Plasma spilled has improved potency and is drawn to you automatically.", statLabel: "Bonus Speed", values: { common: "+100%" } },
    { name: "Hostile Environment", slot: "Duo", element: "Aether", effect: "Your Ω Cast is stronger and follows you, even as you start to Channel it.", statLabel: "Omega Cast Dmg", values: { common: "+100%" } },
    { name: "Heinous Affront", slot: "Duo", element: "Aether", effect: "Inflicting Wounds occasionally also inflicts all your 'after you take damage' effects.", statLabel: "Recharge", values: { common: "6 Sec" } },
    { name: "Universal Donor", slot: "Duo", element: "Aether", effect: "Whenever you exit a Location, keep some of your Plasma bonuses.", statLabel: "Retained", values: { common: "20" } },
    { name: "Coffin Nail", slot: "Duo", element: "Aether", effect: "Your falling blades from Ares fall immediately and deal more damage.", statLabel: "Blade Bonus", values: { common: "+25" } },
    { name: "Arterial Spray", slot: "Duo", element: "Aether", effect: "Your splash effects from Poseidon may hit 2 times.", statLabel: "Chance", values: { common: "25%" } },
    { name: "Fourth Degree", slot: "Duo", element: "Aether", effect: "Your fireball effects from Hestia inflict Wounds with even greater Power.", statLabel: "Bonus Power", values: { common: "+250" } }
  ],
  Demeter: [
    { name: "Ice Strike", slot: "Attack", element: "Water", effect: "Your Attacks deal more damage and inflict Freeze.", statLabel: "Attack Damage", values: { common: "+30%", rare: "+45%", epic: "+60%", heroic: "+75%" } },
    { name: "Ice Flourish", slot: "Special", element: "Water", effect: "Your Specials deal more damage and inflict Freeze.", statLabel: "Special Damage", values: { common: "+40%", rare: "+60%", epic: "+80%", heroic: "+100%" } },
    { name: "Arctic Ring", slot: "Cast", element: "Water", effect: "Your Casts inflict Freeze and repeatedly deal damage to foes in the binding circle.", statLabel: "Cast Damage", values: { common: "10", rare: "15", epic: "20", heroic: "25" } },
    { name: "Frigid Rush", slot: "Sprint", element: "Water", effect: "Your Sprint forms a Gust around you that lingers after you stop.", statLabel: "Gust Damage", values: { common: "4", rare: "6", epic: "8", heroic: "10" } },
    { name: "Tranquil Gain", slot: "Magick", element: "Earth", effect: "After remaining inactive for 0.5 Sec., rapidly restores Magick until you act.", statLabel: "Restoration", values: { common: "50%", rare: "75%", epic: "100%", heroic: "125%" } },
    { name: "Arctic Gale", slot: "Passive", element: "Water", effect: "Your Casts also create a Gust at the binding circle.", statLabel: "Gust Damage", values: { common: "4", rare: "8", epic: "12", heroic: "16" } },
    { name: "Plentiful Forage", slot: "Passive", element: "Earth", effect: "Whenever you gather resources from a Location, restore Health. Receive 1 Mystery Seed now.", statLabel: "Life Restored", values: { common: "10%", rare: "12%", epic: "14%", heroic: "16%" } },
    { name: "Steady Growth", slot: "Passive", element: "Earth", effect: "Whenever you clear enough Encounters, a random Boon you have gains Rarity.", statLabel: "Encounters", values: { common: "6", rare: "5", epic: "4", heroic: "3" } },
    { name: "Snow Queen", slot: "Passive", element: "Earth", effect: "Gain a barrier that stops 1 instance of damage in each Location, but you Prime Magick.", statLabel: "Magick Primed", values: { common: "25", rare: "20", epic: "15", heroic: "10" } },
    { name: "Weed Killer", slot: "Passive", element: "Earth", effect: "Your Ω Attack deals more damage, but uses +10 Magick.", statLabel: "Bonus Damage", values: { common: "+50%", rare: "+75%", epic: "+100%", heroic: "+125%" } },
    { name: "Local Climate", slot: "Passive", element: "Earth", effect: "Your Ω Cast deals more damage. If you are in the binding circle, the bonus is doubled.", statLabel: "Bonus Damage", values: { common: "+20%", rare: "+30%", epic: "+40%", heroic: "+50%" } },
    { name: "Cold Storage", slot: "Passive", element: "Water", effect: "Your Freeze effects last longer.", statLabel: "Freeze Duration", values: { common: "+2s", rare: "+3s", epic: "+4s", heroic: "+5s" } },
    { name: "Frosty Veneer", slot: "Infusion", effect: "While you have at least 6 Water, whenever you would take at least 20 damage, take less.", statLabel: "Reduction", values: { common: "-10" } },
    { name: "Winter Harvest", slot: "Legendary", element: "Earth", effect: "Freeze-afflicted foes shatter at 10% Health, dealing damage in the area.", statLabel: "Shatter Damage", values: { common: "100" } },
    { name: "Hail Storm", slot: "Duo", element: "Aether", effect: "Your Freeze effects also cause lightning bolts to repeatedly strike afflicted foes.", statLabel: "Lightning Dmg", values: { common: "30" } },
    { name: "Cherished Heirloom", slot: "Duo", element: "Aether", effect: "Your Keepsakes are stronger this night (if possible).", statLabel: "Bonus Rank", values: { common: "+1" } },
    { name: "Natural Selection", slot: "Duo", element: "Aether", effect: "Your Boon(s) in the leftmost column gain Lv. spread across however many you got.", statLabel: "Total Bonus Lv", values: { common: "+8" } },
    { name: "Freezer Burn", slot: "Duo", element: "Aether", effect: "Whenever you inflict Freeze on a foe with Scorch, deal damage and remove Scorch.", statLabel: "Scorch Dmg", values: { common: "200%" } },
    { name: "Cryo Pounder", slot: "Duo", element: "Aether", effect: "Your blast effects from Hephaestus deal more damage to Freeze-afflicted foes.", statLabel: "Bonus Blast", values: { common: "+50%" } }
  ],
  Hephaestus: [
    { name: "Volcanic Strike", slot: "Attack", element: "Fire", effect: "Your Attacks can cause a blast that deals 400 damage in the area.", statLabel: "Recharge", values: { common: "12s", rare: "10s", epic: "8s", heroic: "6s" } },
    { name: "Volcanic Flourish", slot: "Special", element: "Fire", effect: "Your Specials can cause a blast that deals 500 damage in the area.", statLabel: "Recharge", values: { common: "15s", rare: "13s", epic: "11s", heroic: "9s" } },
    { name: "Anvil Ring", slot: "Cast", element: "Earth", effect: "Your Casts deal damage 3 times in succession to foes in the binding circle.", statLabel: "Damage", values: { common: "50", rare: "70", epic: "80", heroic: "90" } },
    { name: "Smithy Rush", slot: "Sprint", element: "Fire", effect: "If a foe is near after you Dash, you can cause a blast that deals 200 damage in the area.", statLabel: "Recharge", values: { common: "10s", rare: "9s", epic: "8s", heroic: "7s" } },
    { name: "Tough Gain", slot: "Magick", element: "Earth", effect: "Whenever you take damage, shrug some of it off and restore 150 Magick.", statLabel: "Dmg per Hit", values: { common: "-1", rare: "-2", epic: "-3", heroic: "-4" } },
    { name: "Grand Caldera", slot: "Passive", element: "Fire", effect: "Your blast effects from Hephaestus deal more damage and are 50% larger.", statLabel: "Bonus Damage", values: { common: "+75", rare: "+100", epic: "+125", heroic: "+150" } },
    { name: "Molten Touch", slot: "Passive", element: "Fire", effect: "Your Attacks and Specials deal bonus damage to Armor.", statLabel: "Dmg vs Armor", values: { common: "+40%", rare: "+60%", epic: "+80%", heroic: "+100%" } },
    { name: "Heavy Metal", slot: "Passive", element: "Earth", effect: "Your Weapon deals more damage based on 20% of your Armor, and you gain some now.", statLabel: "Armor Gained", values: { common: "+50", rare: "+75", epic: "+100", heroic: "+125" } },
    { name: "Trusty Shield", slot: "Passive", element: "Earth", effect: "Whenever you enter a Location, gain Armor for that Location, but you Prime 30 Magick.", statLabel: "Starting Armor", values: { common: "+10", rare: "+15", epic: "+20", heroic: "+25" } },
    { name: "Security System", slot: "Passive", element: "Earth", effect: "At the start of each Encounter, you gain Armor that lasts for 7 Sec.", statLabel: "Armor", values: { common: "75", rare: "100", epic: "125", heroic: "150" } },
    { name: "Uncanny Fortitude", slot: "Passive", element: "Earth", effect: "Gain bonus Health based on your Magick limit.", statLabel: "Max Life", values: { common: "+20%", rare: "+30%", epic: "+40%", heroic: "+50%" } },
    { name: "Furnace Blast", slot: "Passive", element: "Fire", effect: "Your blast effects from Hephaestus also inflict Glow on foes.", statLabel: "Glow Bonus", values: { common: "+15%", rare: "+19%", epic: "+25%", heroic: "+26%" } },
    { name: "Martial Art", slot: "Infusion", effect: "Your Attack and Special deal more damage for each Earth you have.", statLabel: "Dmg per Earth", values: { common: "+5%" } },
    { name: "Premium Service", slot: "Legendary", element: "Earth", effect: "Your Aspect of the Nocturnal Arms is even stronger.", statLabel: "Bonus Ranks", values: { common: "+1" } },
    { name: "Brave Face", slot: "Duo", element: "Aether", effect: "Automatically use Magick to resist up to 30% of any damage.", statLabel: "Cost", values: { common: "10 Magick" } },
    { name: "Master Conductor", slot: "Duo", element: "Aether", effect: "Your chain-lightning can bounce off of you and deals increasing damage to foes.", statLabel: "Bounce Dmg", values: { common: "+15%" } },
    { name: "Seismic Servo", slot: "Duo", element: "Aether", effect: "Any Boon effects that recharge overtime recharge faster.", statLabel: "Speed", values: { common: "+35%" } },
    { name: "Chain Reaction", slot: "Duo", element: "Aether", effect: "If you use your blast effects from Hephaestus just after they recharge, they fire 2 times.", statLabel: "Timing", values: { common: "2 Sec" } }
  ],
  Hera: [
    { name: "Sworn Strike", slot: "Attack", element: "Earth", effect: "Your Attacks deal more damage and inflict Hitch.", statLabel: "Attack Damage", values: { common: "+50%", rare: "+60%", epic: "+70%", heroic: "+80%" } },
    { name: "Sworn Flourish", slot: "Special", element: "Earth", effect: "Your Specials deal more damage and inflict Hitch.", statLabel: "Special Damage", values: { common: "+60%", rare: "+70%", epic: "+80%", heroic: "+90%" } },
    { name: "Engagement Ring", slot: "Cast", element: "Air", effect: "Your Casts inflict Hitch and immediately deal damage based on foes in the binding circle.", statLabel: "Damage", values: { common: "20", rare: "30", epic: "40", heroic: "50" } },
    { name: "Nexus Rush", slot: "Sprint", element: "Fire", effect: "Your Sprint inflicts Hitch on surrounding foes, and deals damage when it does.", statLabel: "Damage", values: { common: "60", rare: "90", epic: "120", heroic: "150" } },
    { name: "Born Gain", slot: "Magick", element: "Water", effect: "Whenever you run out of Magick, Prime until the next Location to restore all Magick.", statLabel: "Primed", values: { common: "20", rare: "18", epic: "16", heroic: "14" } },
    { name: "Extended Family", slot: "Passive", element: "Fire", effect: "Your damaging effects from Olympians are stronger for each Boon-giver you have.", statLabel: "Bonus Damage", values: { common: "+3%", rare: "+4%", epic: "+5%", heroic: "+6%" } },
    { name: "Dying Wish", slot: "Passive", element: "Air", effect: "Whenever Hitch-afflicted foes are slain, damage all other Hitch-afflicted foes.", statLabel: "Damage", values: { common: "40", rare: "60", epic: "80", heroic: "100" } },
    { name: "Bridal Glow", slot: "Passive", element: "Water", effect: "Make 1 random Boon become Heroic and give it Lv.", statLabel: "Bonus Lv", values: { common: "+1", rare: "+2", epic: "+3", heroic: "+4" } },
    { name: "Hereditary Bane", slot: "Passive", element: "Water", effect: "Your Hitch effects deal more damage and last +5 Sec.", statLabel: "Hitch Damage", values: { common: "+10%", rare: "+15%", epic: "+20%", heroic: "+25%" } },
    { name: "Rousing Reception", slot: "Passive", element: "Air", effect: "Your Casts damage any foes as they join the Encounter, wherever they appear.", statLabel: "Damage", values: { common: "60", rare: "80", epic: "100", heroic: "120" } },
    { name: "Uncommon Grace", slot: "Passive", element: "Fire", effect: "While none of your other Boons are Common, deal more damage.", statLabel: "Bonus Damage", values: { common: "+10%", rare: "+15%", epic: "+20%", heroic: "+25%" } },
    { name: "Fine Line", slot: "Passive", element: "Earth", effect: "Your Ω Moves create a fissure that deals damage in a long line, but use +15 Magick.", statLabel: "Damage", values: { common: "120", rare: "150", epic: "180", heroic: "210" } },
    { name: "Proper Upbringing", slot: "Infusion", effect: "While you have at least 2 Earth Water Air Fire Elements, all your Common Boons gain Rarity.", statLabel: "Rarity", values: { common: "Rare" } },
    { name: "All Together", slot: "Legendary", element: "Aether", effect: "Gain Earth Water Air Fire Elements, and 1 Infusion Boon for each.", statLabel: "Essences", values: { common: "+1" } },
    { name: "Queen's Ransom", slot: "Duo", element: "Aether", effect: "Give up all your Boons of Zeus. For each, raise Lv. for all your Boons of Hera.", statLabel: "Bonus Lv", values: { common: "+4" } },
    { name: "Ripple Effect", slot: "Duo", element: "Aether", effect: "Your effects from Fine Line and Ocean Swell have a chance to fire 2 times.", statLabel: "Chance", values: { common: "+30%" } },
    { name: "Incandescent Aura", slot: "Duo", element: "Aether", effect: "Whenever you restore Magick during Encounters, damage all Hitch-afflicted foes.", statLabel: "Damage", values: { common: "500%" } }
  ],
  Hermes: [
    { name: "Nimble Limbs", slot: "Passive", element: "Earth", effect: "Your Attack, Special, and Cast are faster.", statLabel: "Speed", values: { common: "+10%", rare: "+15%", epic: "+20%", heroic: "+25%" } },
    { name: "Racing Thoughts", slot: "Passive", element: "Earth", effect: "Your Ω Moves are faster.", statLabel: "Speed", values: { common: "+15%", rare: "+20%", epic: "+25%", heroic: "+30%" } },
    { name: "Winner's Circle", slot: "Passive", element: "Earth", effect: "You Channel your Ω Cast faster and your Casts expire faster.", statLabel: "Speed", values: { common: "+100%", rare: "+125%", epic: "+150%", heroic: "+175%" } },
    { name: "Nitro Boost", slot: "Passive", element: "Fire", effect: "Your Sprint is 15% faster and gives you a barrier that ignores instances of damage.", statLabel: "Hits Blocked", values: { common: "1", rare: "2", epic: "3", heroic: "4" } },
    { name: "Stutter Step", slot: "Passive", element: "Earth", effect: "You can Dash more frequently.", statLabel: "Recovery Speed", values: { common: "+25%", rare: "+30%", epic: "+35%", heroic: "+40%" } },
    { name: "Hasty Retreat", slot: "Passive", element: "Air", effect: "Gain Dodge chance and move speed that increase the more Boons you have.", statLabel: "Per Boon", values: { common: "+0.5%", rare: "+0.75%", epic: "+1%", heroic: "+1.25%" } },
    { name: "Hard Target", slot: "Passive", element: "Air", effect: "Most foes' ranged shots are slower.", statLabel: "Slow", values: { common: "30%", rare: "40%", epic: "50%", heroic: "60%" } },
    { name: "Quick Buck", slot: "Passive", element: "Air", effect: "You find Gold in greater quantities. Receive +100 Gold now, plus the bonus!", statLabel: "Bonus Gold", values: { common: "+20%", rare: "+30%", epic: "+40%", heroic: "+50%" } },
    { name: "Mean Streak", slot: "Passive", element: "Air", effect: "Each time you slay a foe, deal more damage for the next 45 Sec.", statLabel: "Per Foe", values: { common: "+1%", rare: "+1.5%", epic: "+2%", heroic: "+2.5%" } },
    { name: "Travel Deal", slot: "Passive", element: "Fire", effect: "Your first purchase in each Location cost less Gold, and another item appears afterwards.", statLabel: "Discount", values: { common: "-5%", rare: "-10%", epic: "-15%", heroic: "-20%" } },
    { name: "Success Rate", slot: "Passive", element: "Water", effect: "Your chance-base effects are most likely to occur, except for Dodge or Daze.", statLabel: "Chance", values: { common: "30%", rare: "40%", epic: "50%", heroic: "60%" } },
    { name: "Tall Order", slot: "Infusion", effect: "While you have at least 8 Earth, 8 Water, 8 Air, or 8 Fire, you deal more damage.", statLabel: "Infused Dmg", values: { common: "+25%" } },
    { name: "Paid Dues", slot: "Legendary", element: "Air", effect: "Whenever you take damage, you lose Gold before you lose Health.", statLabel: "Cost per Dmg", values: { common: "-3" } }
  ],
  Hestia: [
    { name: "Flame Strike", slot: "Attack", element: "Fire", effect: "Your Attacks inflict Scorch.", statLabel: "Scorch Damage", values: { common: "30", rare: "45", epic: "60", heroic: "75" } },
    { name: "Flame Flourish", slot: "Special", element: "Fire", effect: "Your Specials inflict Scorch.", statLabel: "Scorch Damage", values: { common: "35", rare: "53", epic: "70", heroic: "88" } },
    { name: "Smolder Ring", slot: "Cast", element: "Fire", effect: "Your Casts repeatedly inflict Scorch on foes in the binding circle.", statLabel: "Scorch Damage", values: { common: "40", rare: "60", epic: "80", heroic: "100" } },
    { name: "Heat Rush", slot: "Sprint", element: "Fire", effect: "Your Sprint leaves a cinder trail, and any damage you take from burning is reduced to 1.", statLabel: "Trail Damage", values: { common: "10", rare: "15", epic: "20", heroic: "25" } },
    { name: "Cardio Gain", slot: "Magick", element: "Fire", effect: "Whenever your Attack or Special deal damage, restore Magick.", statLabel: "Magick Restored", values: { common: "4", rare: "6", epic: "8", heroic: "10" } },
    { name: "Highly Flammable", slot: "Passive", element: "Fire", effect: "Whenever you inflict Scorch on a foe for the first time, inflict more.", statLabel: "Bonus Scorch", values: { common: "+80", rare: "+120", epic: "+160", heroic: "+200" } },
    { name: "Glowing Coal", slot: "Passive", element: "Fire", effect: "Hold Cast to aim a fireball that explodes on impact. The binding circle forms there.", statLabel: "Blast Damage", values: { common: "60", rare: "90", epic: "120", heroic: "150" } },
    { name: "Controlled Burn", slot: "Passive", element: "Fire", effect: "Your Ω Special also launches a fireball, but uses +10 Magick.", statLabel: "Blast Damage", values: { common: "100", rare: "150", epic: "200", heroic: "250" } },
    { name: "Flash Fry", slot: "Passive", element: "Fire", effect: "Your foes perish in a blast that damages any surrounding foes.", statLabel: "Blast Damage", values: { common: "60", rare: "90", epic: "120", heroic: "150" } },
    { name: "Hot Pot", slot: "Passive", element: "Fire", effect: "Gain a chance to Dodge, which is doubled against Scorch-afflicted foes.", statLabel: "Dodge Chance", values: { common: "+4%", rare: "+5%", epic: "+6%", heroic: "+7%" } },
    { name: "Pyro Technique", slot: "Passive", element: "Fire", effect: "Your Scorch effects deal damage faster.", statLabel: "Rate", values: { common: "+50%", rare: "+75%", epic: "+100%", heroic: "+125%" } },
    { name: "Snuffed Candle", slot: "Passive", element: "Fire", effect: "You deal more damage to foes that are nowhere near other foes.", statLabel: "Damage", values: { common: "+15%", rare: "+18%", epic: "+21%", heroic: "+24%" } },
    { name: "Slow Cooker", slot: "Infusion", effect: "Your Attacks and Specials gain Power the more Fire you have.", statLabel: "Power/Fire", values: { common: "+2" } },
    { name: "Fire Away", slot: "Legendary", element: "Fire", effect: "Your Casts destroy many foes' ranged shots, and inflict Scorch on the attacking foes.", statLabel: "Scorch Dmg", values: { common: "400" } },
    { name: "Thermal Dynamics", slot: "Duo", element: "Aether", effect: "Your Blitz effects also inflict Scorch whenever they deal damage.", statLabel: "Scorch Dmg", values: { common: "160" } },
    { name: "Scalding Vapor", slot: "Duo", element: "Aether", effect: "If foes with Froth are struck by your fire effects from Hestia, they are engulfed in Steam.", statLabel: "Steam Dmg", values: { common: "20" } }
  ],
  Poseidon: [
    { name: "Wave Strike", slot: "Attack", element: "Water", effect: "Your Attacks hit foes with a splash that knocks other foes away.", statLabel: "Splash Damage", values: { common: "20", rare: "25", epic: "30", heroic: "35" } },
    { name: "Wave Flourish", slot: "Special", element: "Water", effect: "Your Specials hit foes with a splash that knocks other foes away.", statLabel: "Splash Damage", values: { common: "30", rare: "40", epic: "50", heroic: "60" } },
    { name: "Tidal Ring", slot: "Cast", element: "Water", effect: "Your Casts also immediately hit foes with a powerful splash that inflicts Froth.", statLabel: "Splash Damage", values: { common: "60", rare: "90", epic: "120", heroic: "150" } },
    { name: "Breaker Rush", slot: "Sprint", element: "Water", effect: "Whenever you Sprint, hit the first foe you run into with a blast that knocks foes away.", statLabel: "Blast Damage", values: { common: "80", rare: "100", epic: "120", heroic: "140" } },
    { name: "Flood Gain", slot: "Magick", element: "Water", effect: "Your Ω Moves make you briefly restore any Magick you use, repeatable after 8 Sec.", statLabel: "Flood Duration", values: { common: "4s", rare: "5s", epic: "6s", heroic: "7s" } },
    { name: "Hydraulic Might", slot: "Passive", element: "Water", effect: "At the start of each Encounter, your Attacks and Specials are stronger for 10 Sec.", statLabel: "Bonus Damage", values: { common: "+100%", rare: "+133%", epic: "+166%", heroic: "+200%" } },
    { name: "Buried Treasure", slot: "Passive", element: "Water", effect: "Any Minor Finds and Gold are worth more, and you receive Gold, Health, and Bones now.", statLabel: "Reward Value", values: { common: "+50%", rare: "+75%", epic: "+100%", heroic: "+125%" } },
    { name: "High Surf", slot: "Passive", element: "Water", effect: "Hit surrounding foes with a powerful splash as they start to strike, but you Prime 30 Magick.", statLabel: "Splash Damage", values: { common: "40", rare: "60", epic: "80", heroic: "100" } },
    { name: "Sea Star", slot: "Passive", element: "Water", effect: "Whenever you claim rewards other than Boons, Daedalus Hammer, or rare resources, a copy may appear.", statLabel: "Chance", values: { common: "25%", rare: "30%", epic: "35%", heroic: "40%" } },
    { name: "Slippery Slope", slot: "Passive", element: "Water", effect: "Your splash effects from Poseidon also inflict Froth, and Froth deals more damage.", statLabel: "Froth Damage", values: { common: "+20%", rare: "+50%", epic: "+80%", heroic: "+110%" } },
    { name: "Geyser Spout", slot: "Passive", element: "Water", effect: "Your Ω Cast gains Power and knocks foes away.", statLabel: "Bonus Power", values: { common: "150", rare: "200", epic: "250", heroic: "300" } },
    { name: "Ocean Swell", slot: "Passive", element: "Water", effect: "Your Ω Moves also launch a wide wave ahead that knocks foes away, but use +5 Magick.", statLabel: "Wave Damage", values: { common: "40", rare: "60", epic: "80", heroic: "100" } },
    { name: "Water Fitness", slot: "Infusion", effect: "Gain Health for each Water you have.", statLabel: "Max Life/Water", values: { common: "+15" } },
    { name: "King Tide", slot: "Legendary", element: "Water", effect: "Your splash effects from Poseidon are larger and deal bonus damage to Guardians.", statLabel: "Dmg vs Guardian", values: { common: "+200%" } },
    { name: "Killer Current", slot: "Duo", element: "Aether", effect: "Your lightning deals more damage to Froth-afflicted foes.", statLabel: "Lightning Dmg", values: { common: "+30%" } }
  ],
  Zeus: [
    { name: "Heaven Strike", slot: "Attack", element: "Air", effect: "Your Attacks inflict Blitz.", statLabel: "Blitz Damage", values: { common: "80", rare: "120", epic: "160", heroic: "200" } },
    { name: "Heaven Flourish", slot: "Special", element: "Air", effect: "Your Specials inflict Blitz.", statLabel: "Blitz Damage", values: { common: "100", rare: "130", epic: "160", heroic: "190" } },
    { name: "Storm Ring", slot: "Cast", element: "Air", effect: "Your Casts cause lightning bolts to repeatedly strike 1 foe at a time in the binding circle.", statLabel: "Bolt Damage", values: { common: "25", rare: "30", epic: "35", heroic: "40" } },
    { name: "Thunder Rush", slot: "Sprint", element: "Air", effect: "Dashing causes surrounding foes to be struck by lightning bolts.", statLabel: "Bolt Damage", values: { common: "20", rare: "25", epic: "30", heroic: "35" } },
    { name: "Ionic Gain", slot: "Magick", element: "Air", effect: "In each Encounter, an Aether Font appears in the area and restores all Magick when used.", statLabel: "Reappearance", values: { common: "10s", rare: "9s", epic: "8s", heroic: "7s" } },
    { name: "Power Surge", slot: "Passive", element: "Air", effect: "Whenever you use Magick, a random surrounding foe is struck by lightning.", statLabel: "Bolt Damage", values: { common: "20", rare: "30", epic: "40", heroic: "50" } },
    { name: "Divine Vengeance", slot: "Passive", element: "Air", effect: "After you take damage, your foe is struck by lightning, and again 50% of the time.", statLabel: "Bolt Damage", values: { common: "100" } },
    { name: "Lightning Lance", slot: "Passive", element: "Air", effect: "Hold Cast to aim where the binding circle appears. Foes within are struck by lightning.", statLabel: "Bolt Damage", values: { common: "50", rare: "70", epic: "90", heroic: "110" } },
    { name: "Static Shock", slot: "Passive", element: "Air", effect: "Your strikes emit chain-lightning that bounces up to 4 times, but you Prime 50 Magick.", statLabel: "Chain Damage", values: { common: "10", rare: "15", epic: "20", heroic: "25" } },
    { name: "Double Strike", slot: "Passive", element: "Air", effect: "Your lightning bolt effects may strike 2 more times.", statLabel: "Bonus Chance", values: { common: "+10%", rare: "+15%", epic: "+20%", heroic: "+25%" } },
    { name: "Arc Flash", slot: "Passive", element: "Air", effect: "Damage from Ω Moves immediately activates Blitz effects and makes them stronger.", statLabel: "Bonus Damage", values: { common: "+30%", rare: "+40%", epic: "+50%", heroic: "+60%" } },
    { name: "Electric Overload", slot: "Passive", element: "Air", effect: "Your chain-lightning deals more damage and bounces up to +3 times.", statLabel: "Chain Damage", values: { common: "+20%", rare: "+30%", epic: "+40%", heroic: "+50%" } },
    { name: "Air Quality", slot: "Infusion", effect: "While you have at least 5 Air, you can never deal less damage than the limit.", statLabel: "Min Damage", values: { common: "50" } },
    { name: "Shocking Loss", slot: "Legendary", element: "Air", effect: "Whenever you first deal damage to susceptible foes, you may destroy them outright.", statLabel: "Chance", values: { common: "25%" } },
    { name: "King's Ransom", slot: "Duo", element: "Aether", effect: "Give up all your Boons of Hera. For each, raise Lv. for all your Boons of Zeus.", statLabel: "Bonus Lv", values: { common: "+4" } }
  ]
};
