
export interface HammerUpgrade {
  name: string;
  description: string;
}

export const HAMMER_DATABASE: Record<string, HammerUpgrade[]> = {
  staff: [
    { name: "Wicked Thrasher", description: "Your Attacks have +30 Power." },
    { name: "Extending Wallop", description: "Your Attack has more range and deals +100% damage to distant foes." },
    { name: "Melting Swipe", description: "Your Dash-Strike hits a larger area and deals +900 damage to Armor." },
    { name: "Dual Moonshot", description: "Your Specials fire 2 projectiles, but have -40% range." },
    { name: "Shimmering Moonshot", description: "Your Specials bounces toward up to +2 foes, dealing +10% damage for each hit." },
    { name: "Cross Cataclysm", description: "Your Omega Attack deals +50% damage and also strikes sideways." },
    { name: "Rapid Thrasher", description: "Your Attacks are 50% faster." },
    { name: "Rapid Moonshot", description: "Your Specials are 25% faster." },
    { name: "Vampiric Cataclysm", description: "Whenever you slay a foe with your Omega Attack, restore 5 Health." },
    { name: "Giga Moonburst", description: "You can Channel +30 Magick in your Omega Special to deal +300% damage in a larger area." },
    { name: "Aetheric Moonburst", description: "Your Omega Special gains a Power Shot that deals +50% damage and restores 20 Magick." },
    { name: "Mirrored Thrasher", description: "Your Attacks hit 2 times, but use 5 Magick." },
    { name: "Soulfilled Ankh", description: "Your Attacks have +5 Power and hit a larger area." },
    { name: "Mirrored Ankh", description: "Your Omega Attack creates +1 damage field ahead of the first." },
    { name: "Scarab Etchings", description: "Lone Shades deal +50 damage and have 75% chance to reappear after striking a foe." },
    { name: "Pharaoh Etchings", description: "Lone Shades deal +50% damage and launch at foes struck by Special." },
  ],
  blades: [
    { name: "Sweeping Ambush", description: "Your Omega Attack deals +400% damage in a wider area, but uses +20 Magick." },
    { name: "Dancing Knives", description: "Your Specials deal +15% damage and each hit bounces toward up to 2 more foes." },
    { name: "Sureshot Flurry", description: "Your Omega Special fires each shot straight ahead and your Specials have +30% range." },
    { name: "Rapid Onslaught", description: "Your Attacks are 35% faster." },
    { name: "Melting Sickle", description: "Each hit from your Special deals +500 damage to Armor." },
    { name: "Skulking Onslaught", description: "Your Attacks deal +150% damage striking foes from behind." },
    { name: "Reaper Knives", description: "Your Specials have +15 Power and deal damage in a wider area." },
    { name: "Hidden Knives", description: "Your Specials deal +20% damage and your Omega Special fires +3 shots." },
    { name: "Final Slice", description: "The last strike in your Attack sequence deals +300% damage in a larger area." },
    { name: "Wicked Onslaught", description: "Your Attacks have +20 Power." },
    { name: "Sudden Flurry", description: "You Channel your Omega Special 40% faster." },
    { name: "Trick Knives", description: "Your Dash-Strike also fires your Special 3 times at once in a fan pattern." },
    { name: "Phantom Etchings", description: "Your Blood Triad deals +222 damage." },
    { name: "Banshee Brand", description: "Your Blood Triad has 33% chance to strike once more." },
    { name: "Sinister Pinion", description: "Your Specials repeatedly deal damage 100% faster." },
  ],
  axe: [
    { name: "Furious Whirlwind", description: "You Channel your Omega Attack faster, and move 50% faster while it is active." },
    { name: "Sudden Cleaver", description: "You Channel your Omega Special 25% faster." },
    { name: "Rapid Slash", description: "Your Attack is 30% faster." },
    { name: "Executioner's Chop", description: "The final move in your Attack sequence hits 2 times, but uses 20 Magick." },
    { name: "Hell Splitter", description: "Your Attack has +300 Power, but the 3-strike sequence becomes only the final chop." },
    { name: "Seething Marauder", description: "Your Attacks also deals 60 damage to surrounding foes, for each and every strike." },
    { name: "Psychic Whirlwind", description: "During your Omega Attack, you are free to use your Attacks and Specials." },
    { name: "Melting Shredder", description: "Each hit from your Special deals +300 damage to Armor." },
    { name: "Siege Shredder", description: "Your Special strikes farther ahead and deals +150% damage." },
    { name: "Giga Cleaver", description: "Your Omega Special fires 2 times in succession, but costs +15 Magick." },
    { name: "Dashing Heave", description: "Your Dash-Strike hits 2 times in an area around you." },
    { name: "Colossus Slash", description: "Your Attacks have +10 Power and you take -20% damage while using them." },
    { name: "Iron Core", description: "Your Berserk lasts +2 Sec. and restores +1 Health per foe struck." },
    { name: "Heaven Splitter", description: "Your Attacks hits 2 times, but the 5-strike sequence becomes only the first slam." },
  ],
  flames: [
    { name: "Hidden Helix", description: "Your Specials creates +1 projectile." },
    { name: "Clean Coil", description: "You Channel your Omega Special 20% faster, and it uses -10 Magick." },
    { name: "Furious Blaze", description: "While you Channel your Attacks, you move and fire 20% faster." },
    { name: "Dividing Blaze", description: "Your Attacks split in 2 the first time they strike foes." },
    { name: "Inverted Blaze", description: "Your Attacks linger for +2 Sec. and launch back towards you after you Dash." },
    { name: "Sudden Burst", description: "You Channel your Omega Attack 50% faster, and it uses -1 Magick." },
    { name: "Rising Helix", description: "Your Specials grow in size and deal up to +25% damage the longer they are active." },
    { name: "Whirling Helix", description: "Projectiles from your Specials orbit 20% faster." },
    { name: "Leaden Blaze", description: "Your Attacks knock foes away and have +10 Power." },
    { name: "Demonic Cell", description: "As long as you Sprint, your Attacks and Specials have +5 Power." },
  ],
  skull: [
    { name: "Bolstered Array", description: "Gain +2 Shells." },
    { name: "Fetching Array", description: "Your Shells fly back to you automatically and 100% faster." },
    { name: "Melting Tackle", description: "Your Special deals +600 damage to Armor." },
    { name: "Wide Grin", description: "Your Attacks fire your Shells all at once in a spread pattern." },
    { name: "Rapid Driver", description: "Your Specials are 35% faster." },
    { name: "Colossus Driver", description: "Your Specials have +30 Power and you take -30% damage while using them." },
    { name: "Mega Driver", description: "Your Specials launch you ahead faster and deal +50% damage." },
    { name: "Twisting Crash", description: "After your Omega Special projectiles fire outward, they fire inward." },
    { name: "Boosted Ignition", description: "After your Dash or Specials, your Attacks are faster and have +15 Power." },
    { name: "Volatile Array", description: "Whenever your Shells land, they deal 50% of your Attack damage around them." },
    { name: "Possessed Array", description: "Your Shells fire your Omega Attack whenever retrieved, but make you lose 25 Magick." },
    { name: "Looming Ignition", description: "Your Attacks gain +50% damage and blast size over 0.7 Sec. before they explode." },
    { name: "Venerated Relic", description: "Your Valkyrie form lasts +3 Sec." },
    { name: "Leering Glance", description: "Your Attack shots bounce toward +1 and deal +15% damage on the successive hit." },
    { name: "Runic Driver", description: "Your Specials fly faster and deal +15% damage for each foe struck." },
    { name: "Garmr Gaze", description: "Your Attacks shoot +25% farther and deal +25% damage." },
    { name: "Helheim Charge", description: "Your Omega Attack fires +2 times in succession." },
  ],
  coat: [
    { name: "Melting Cross", description: "Your Attack deal +250 damage to Armor." },
    { name: "Rapid Frame", description: "Your Attacks are 35% faster." },
    { name: "Reaper Frame", description: "Your Attacks have +10 Power and deal damage in a larger area." },
    { name: "Siege Frame", description: "Your Attacks deal +30% damage and reach farther ahead." },
    { name: "World Collider", description: "Your fully-charged Omega Attack has +100 Power." },
    { name: "Exhaust Riser", description: "Your Dash-Strike hits +3 times." },
    { name: "Shimmering Rockets", description: "Your Specials bounce toward up to 2 more foes." },
    { name: "Furious Rockets", description: "Your Specials launch and fly 80% faster." },
    { name: "Launcher Frame", description: "Whenever your Attacks strike foes, your Special has 25% chance to fire automatically." },
    { name: "Counter Barrage", description: "After blocking with your Omega Attack, your Special auto-fires 5 shots, reloading in 3 Sec." },
    { name: "Sudden Salvo", description: "Your Omega Special locks on faster and uses -20% Magick." },
    { name: "Ripper Rockets", description: "Your Specials briefly gain +5 Power for up to 5 consecutive hits to the same foe." },
    { name: "Elephant Rockets", description: "Your Specials have +30 Power and fly dead ahead." },
    { name: "Counter Supreme", description: "After blocking with your Omega Attack, become Destructive by up to +3 ranks." },
    { name: "Awakened Rockets", description: "Absorbing Omega Special blasts also creates blasts from your Special, but you lose 5 Magick." },
    { name: "Mooncrest Riser", description: "Your Dash-Strike hits a larger area and deals +40% damage." },
    { name: "Chakra Collider", description: "Your Omega Attack gains a Power Shot that deals +150% damage." },
  ],
};
